### PR TITLE
Components

### PR DESCRIPTION
**Pull request by rbhatt1999**
# In this pull required following changes done:

- Removed all unused files
- Crate Calculator component
- Create CalculatorButton Component
- Create TextInput Component
- Used all of the components to design he calculator UI

### CODE REVIEW

**Review by Gopxfs — CHANGES_REQUESTED** [review]
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi @rbhatt1999 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights :rocket:
✔️ No linter errors.
✔️ Great code structure. Well done!
✔️ Followed the wireframe 😉.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gopxfs** [comment]
https://github.com/rbhatt1999/math-magician/blob/dev/README.md?plain=1#L4-L8

Your readme is looking professional, but it can be improved 😉. To do so: 
- [ ] Please remove the Microverse logo (feel free to add your own!): 
image 


- [ ] Kindly avoid empty sections: 
image


- [ ] Please add a description to your project. What is math magician?
image


- [ ] [OPTIONAL] Nice job adding the corresponding link to your social media! I recommend that you change the link name from `githubhandle` to your name:
image
e.g. Github: [@rbhatt199]()


- [ ] Make sure to add the corresponding path to your MIT since it isn't working: :wink:: 
image

**Comment by Gopxfs** [comment]
As requested in the project requirements: 
image  

Please make sure to remove all the boilerplate elements 😄! I've made a checklist for you 😉: 
- [x] src/App.css 
- [x] src/App.test.js 
- [x] src/setupTests.js 
- [x] src/reportWebVitals.js 
- [x] src/logo.svg 
- [x] public/manifest.json 
- [x] public/logo192.png 
- [x] public/logo512.png

**Review by Gopxfs — CHANGES_REQUESTED** [review]
# ♻️ STATUS: REQUIRED CHANGES ♻️   

## Hi @rbhatt1999 👋,

You've done well implementing some of the requested changes 👏 , but there are still some which haven't been addressed yet.



## Highlights :rocket:
✔️ Implemented some of the changes requested by the previous reviewer.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gopxfs** [comment]
- [x] Please make sure to also remove the link to the FAQ section:
image

- [ ] Please remove the Microverse logo. You can add your own logo if you want.

Take into account that the Microverse logo needs to be removed since it is a placeholder for your logo.

**Review by gemmen29 — APPROVED** [review]
Hi @rbhatt1999, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 



## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
